### ISSUE TITLE
Consider mirroring aws-cdk versioning numbers

### ISSUE THREAD

**Issue by BDQ** [elegantdevelopment/aws-cdk-dynamodb-seeder#12]
First, thank you for contributing this module to the community. We appreciate it!

**Is your feature request related to a problem? Please describe.**
The problem is matching versions of this module with the CDK versions. For example, I just tried adding this module to a project using CDK `1.25.0` 

Given your current release is compatible with `1.26.0`, my project won't compile with your latest version.

So, now figuring out what version number of this module that corresponds to `1.25.0` is error prone and confusing.

**Describe the solution you'd like**
If this module released versions matching CDK's, things would be a lot more straightforward.

FYI, this is something we follow with this module here: https://github.com/mobileposse/auto-delete-bucket#versioning

**Comment by jsdtaylor** [comment]
Hey @BDQ 

Cheers! :) So the main issue with this (and it's something I thought of when I first released this) is what happens when I need to release minor enhancements or fixes.

Let's take a scenario:

We version this package as 1.26.0 to match aws-cdk@1.26.0. We then release a breaking change but we aren't yet supporting a different version of CDK. 🤷‍♂

We either:

1. Bump the version up a major increment (satisfying [Semantic Versioning](https://semver.org/)) or even a minor one, or
2. Keep the version the same (or increase the patch number, and thereby breaking semver)

**Comment by BDQ** [comment]
I totally agree mirroring versions isn't going to align with SemVer, I don't think CDK community has a good answer to versioning right now so it hard to know which way to go.

In our case (in auto-delete-bucket) we favoured ease of use/adoption over strict semver adherence.

**Comment by jsdtaylor** [comment]
Well, I was 50:50 and you're the first person to challenge it. So we'll go with that and see how we fare! :)

**Comment by BDQ** [comment]
Awesome! Thanks @jsdtaylor

**Comment by jsdtaylor** [comment]
@BDQ fyi - see #14 (sorry about that!)

It'll remove a prop from the constructor, so it *is* a breaking change 🙈. On the plus side, it solves the first bug I had! (`aws-cdk@1.26.0` fixed it)
